DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

Mxoinline3/urls.py
from django.conf.urls import url
import xadmin
from django.views.generic import TemplateView
from users.views import LoginView,LogoutView,RegisterView,ForgetPwdView,ActiveUserView,ResetView,ModifyPwdView,IndexView
from django.conf.urls import url,include
from django.views.static import serve
from Mxoinline3.settings import MEDIA_ROOT


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    # 富文本编辑器
    url('ueditor/',include('DjangoUeditor.urls')),
    # TemplateView.as_view会将template转换为view
    url('^$',IndexView.as_view(),name='index'),
    url('^login/$',LoginView.as_view(),name='login'),
    # 用户个人中心
    url('^users/',include('users.urls',namespace='users')),
    # 登出
    url('^logout/$',LogoutView.as_view(),name='logout'),
    # 注册
    url('^register/$',RegisterView.as_view(),name='register'),
    url('^captcha/',include('captcha.urls')),
    url('^forget/$',ForgetPwdView.as_view(),name= 'forget_pwd'),
    url('^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name = 'user_active'),
    url('^reset/(?P<active_code>.*)/$',ResetView.as_view(),name='reset_pwd'),
    url('^modify_pwd/$',ModifyPwdView.as_view(),name='modify_pwd'),
    # 课程机构
    url('^org/', include('organization.urls',namespace='org')),
    # 处理图片显示的url,使用django自带serve，传入参数告诉它去那个路径找，我们有配置好的路径MEDIAROOT
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # 静态文件
    # url(r'^static/(?P<path>.*)$',serve,{'document_root':STATIC_ROOT}),
    # 公开课
    url(r'^course/',include('courses.urls',namespace='course'))
]

# 全局404页面配置
handler404 = 'users.views.pag_not_found'
# 全局500页面配置
handler500 = 'users.views.page_error'

apps/courses/urls.py
# encoding: utf-8
__author__ = 'ZMY'
__date__ = '2018/6/14 21:01'

from courses.views import CourseListView,CourseDetailView,CourseInfoView,CommentsView,AddCommentsView,VideoPlayView
from django.conf.urls import url

app_name = 'courses'

urlpatterns = [
    # 公开课列表
    url(r'^list/$',CourseListView.as_view(),name='course_list'),
    # 课程详情页
    url('^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="course_detail"),
    # 章节信息
    url(r'^info/(?P<course_id>\d+)/$',CourseInfoView.as_view(),name='course_info'),
    # 课程评论
    url(r'^comments/(?P<course_id>\d+)/$',CommentsView.as_view(),name='course_comments'),
    # 添加评论
    url(r'all_comment/',AddCommentsView.as_view(),name='add_comment'),
    # 课程视频播放页
    url(r'^video/(?P<video_id>\d+)/$',VideoPlayView.as_view(),name='video_play'),
]

apps/organization/urls.py
# encoding: utf-8
__author__ = 'ZMY'
__date__ = '2018/5/31 8:03'

from organization.views import OrgView,AddUserAskView,OrgHomeView,OrgCourseView,TeacherListView
from organization.views import OrgDescView,OrgTeacherView,AddFavView,TeacherDetailView
from django.conf.urls import url

app_name = 'organization'

urlpatterns = [
    # 课程机构
    url('^list/',OrgView.as_view(),name='org_list'),
    # 添加我要学习
    url('^add_ask/',AddUserAskView.as_view(),name='add_ask'),
    # home页面,取纯数字
    url(r'home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    # 访问机构课程
    url('^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),
    # 访问机构描述
    url('^desc/(?P<org_id>\d+)/$',OrgDescView.as_view(), name='org_desc'),
    # 访问机构讲师
    url('^teacher/(?P<org_id>\d+)/$',OrgTeacherView.as_view(),name='org_teacher'),
    # 机构收藏
    url('^add_fav/',AddFavView.as_view(),name='add_fav'),
    # 讲师列表
    url(r'teacher_list/',TeacherListView.as_view(),name='teacher_list'),
    # 讲师详情
    url(r'^teacher/detail/(?P<teacher_id>\d+)/',TeacherDetailView.as_view(),name='teacher_detail')

]

apps/users/urls.py
# encoding: utf-8
__author__ = 'ZMY'
__date__ = '2018/6/28 8:46'

from .views import UserInfoView,UserMyCourse,UploadImageView,UpdatePwdView,SendEmailCodeView,UpdateEmailView
from .views import MyFavOrgView,MyFavTeacherView,FavCourse,MyMessageView
from django.conf.urls import url

app_name = 'users'

urlpatterns = [
    # 用户信息
    url(r'^info/$',UserInfoView.as_view(),name='user_info'),
    # 用户头像
    url(r'^image/upload/$',UploadImageView.as_view(),name='image_upload'),
    # 用户密码修改
    url(r'^update/pwd/$',UpdatePwdView.as_view(),name='update_pwd'),
    # 邮箱验证码
    url(r'^sendemail_code/$',SendEmailCodeView.as_view(),name='sendemail_code'),
    # 修改邮箱
    url(r'^update_email/$',UpdateEmailView.as_view(),name='update_email'),
    # 用户课程
    url(r'^mycourse/$',UserMyCourse.as_view(),name='user_mycourse'),
    # 用户收藏课程机构
    url(r'^fav_org/$',MyFavOrgView.as_view(),name='fav_org'),
    # 用户收藏讲师
    url(r'^fav_teacher/$',MyFavTeacherView.as_view(),name='fav_teacher'),
    # 用户收藏公共课
    url(r'^fav_course/$',FavCourse.as_view(),name='fav_course'),
    # 用户消息
    url(r'^message/$',MyMessageView.as_view(),name='message')

]

apps/courses/models.py
# encoding: utf-8
from django.db import models
from datetime import datetime
from organization.models import CourseOrg,Teacher
from DjangoUeditor.models import UEditorField


# 课程信息
class Course(models.Model):
    DEGREE_CHOICES = (
        ('cj','初级'),
        ('zj','中级'),
        ('gj','高级'),
    )
    course_org = models.ForeignKey(CourseOrg,verbose_name='所属机构',null=True,blank=True)
    name = models.CharField(max_length=50,verbose_name='课程名')
    teacher = models.ForeignKey(Teacher,verbose_name='讲师',null=True,blank=True)
    you_need_know = models.CharField(max_length=300,default='一颗勤学的心是本课程必要前提',verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=300,default='要乖乖乖哦0.0',verbose_name='老师告诉你')
    desc = models.CharField(max_length=300,verbose_name='课程描述')
    tag = models.CharField(max_length=15,verbose_name='课程标签',default='')
    category = models.CharField(max_length=20,default="后端开发",verbose_name='课程类别')
    # 富文本编辑器领域
    detail = UEditorField(verbose_name='课程详情',width=600,height=300,imagePath="courses/ueditor/",filePath='courses/ueditor/',default='')
    is_banner = models.BooleanField('是否轮播',default=False)
    degree = models.CharField(choices=DEGREE_CHOICES,max_length=2)
    # 使用分钟做后台记录（存储最小单位）前台转换
    learn_times = models.IntegerField(default=0,verbose_name='学习时长（分钟数)')
    # 保存学习人数：点击开始学习才算
    students = models.IntegerField(default=0,verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0,verbose_name='收藏人数')
    image = models.ImageField(
        upload_to='courses/%Y/%m',
        verbose_name='封面图',
        max_length=100,
    )
    # 保存点击量,点击页面就算
    click_nums = models.IntegerField(default=0,verbose_name='点击数')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    def get_zj_nums(self):
        # 获取课程章节数的方法 lesson_ste 反向取值
        return self.lesson_set.all().count()
    get_zj_nums.short_description = '章节数' # 后台显示的名称

    def go_to(self):
        from django.utils.safestring import mark_safe
        # mark_safe后就不用转义
        return mark_safe("<a href='http://zhongminyong.tech/'>跳转</a>")
    go_to.short_description = '跳转'

    # 获取学习这门课程的用户
    def get_learn_users(self):
        # 谁的里面添加了Course（自己）做外键，它都可以取出来(现在是反向取）
        return self.usercourse_set.all()

    # 获取课程章节
    def get_course_lesson(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name


#章节
class Lesson(models.Model):
    # 因为一个课程对应很多章节。所以在章节表中将课程设置为外键。
    # 作为一个字段来让我们可以知道这个章节对应哪个课程
    course = models.ForeignKey(Course,verbose_name='课程')
    name = models.CharField(max_length=100,verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    # 获取章节视频
    def get_lesson_video(self):
        return self.video_set.all()

    def __str__(self):
        return '<<{0}>>课程的章节 >> {1}'.format(self.course,self.name)

    class Meta:
        verbose_name='章节'
        verbose_name_plural = verbose_name


#每章视频
class Video(models.Model):
    # 因为一个章节对应很多视频。所以在视频表中将章节设置为外键
    # 作为一个字段来存储让我们可以知道这个视频对应哪个章节。
    lesson = models.ForeignKey(Lesson,verbose_name='章节')
    name = models.CharField(max_length=100,verbose_name='视频名')
    url = models.CharField(max_length=200,default='http://zhongminyong.tech',verbose_name='访问地址')
    learn_times = models.IntegerField(default=0,verbose_name='学习时长（分钟数)')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    image = models.FileField(
        default='',
        upload_to= "teacher/%Y/%m",
        verbose_name='视频',
        max_length= 255,
        null= True,
        blank= True,
    )

    def __str__(self):
        return '{0}章节的视频 >> {1}'.format(self.lesson,self.name)

    class Meta:
        verbose_name = '视频'
        verbose_name_plural=verbose_name


# 课程资源
class CourseResource(models.Model):
    # 因为一个课程对应很多资源，所以在课程资源表中将课程设置为外键
    # 作为一个字段来让我们知道这个资源对应哪个课程
    course = models.ForeignKey(Course,verbose_name='课程')
    name = models.CharField(max_length=100,verbose_name='名称')
    # 这里定义成文件类型field,后台管理系统中会直接有上传的按钮。
    # FileField也是一个字符串类型，要指定最大长度。
    download = models.FileField(
        upload_to='course/%Y/%m',
        verbose_name='资源文件',
        max_length=100
    )
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        verbose_name='课程资源'
        verbose_name_plural=verbose_name


# 显示轮播图课程
class BannerCourse(Course):
    class Meta:
        verbose_name = '轮播课程'
        verbose_name_plural = verbose_name
        # 设置proxy=True，这样就不会再生成一张表，同时还具有Model的功能
        proxy = True

templates/index.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_bread %}
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}
{% block content %}

    <div class="banner">
			<div class="wp">
				<div class="fl">

					<div class="imgslide">
						<ul class="imgs">
                        {% for banner in all_banners %}
                            <li>
                                    <a href="http://www.imooc.com">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                        {% endfor %}
						</ul>
					</div>

					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                 {% for banner_courses in banner_courses %}
                                    <li>
                                        <a href="course-detail.html">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_courses.image }}" />
                                        </a>
                                    </li>
                                 {% endfor %}
                                    
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for courses in courses %}
                            <div class="module1_3 box">
                                <a href="{% url 'course:course_detail' courses.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ courses.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' courses.id %}">
                                        <h2 title="django入门">{{ courses.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ courses.is_banner }}</i></span>
                                    <span class="fr">学习人数：{{ courses.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网">ZMY慕学网</span>
                                    <span class="star fr">0</span>
                                </div>
                            </div>
                            {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="org-list.html">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for course_org in  course_org %}
                                <li class="">
                                    <a href="{% url 'org:org_home' course_org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>全国知名</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="慕课网">{{ course_org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页 - 慕课网{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
                    <div class="top">
                {% if request.user.is_authenticated %}
                 <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ user.nick_name }}</h2>
	                                    <p>{{ user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
             {% else %}
                 <div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>



                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="/login/">登录</a>



                 </div>
				</div>
             {% endif %}


    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    {{ course_org.name }}
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if has_fav %}已收藏
                 {% else %}收藏
                 {% endif %}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>
    {% block right_form %}

    {% endblock %}
    </div>
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js'%}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/org/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status== 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this),{{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static '' %}images/',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}





{% block right_conent %}
<section>
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:fav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:fav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:fav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for fav_course in course %}
                        <div class="module1_5 box">
                            <a href="course-detail.html">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ fav_course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ fav_course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ fav_course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ fav_course.course_org }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>


	</div>
</section>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}

{% block courstom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_conent %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:fav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:fav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:fav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    
                    <div class="messages butler_list company company-fav-box">
                        {% for org in org_list %}
                        <dl class="des fr">
                            <dt>
                                <a href="org-detail-homepage.html">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="org-detail-homepage.html">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="1"></div>
                            </dd>
                        </dl>
                        {% endfor %}
                    </div>

                    
                </div>
            </div>
        </div>
{% endblock %}